### PR TITLE
fix: sharing text with app

### LINKED ISSUE #157: Sharing to Vikunja causes error
When I try to share a page or something to Vikunja it throws an error. The error goes by so fast I can not read it. 

Expected: url of website now available as task that I can save in the inbox. 

Actual: It just throws an error and leaves me at the inbox.

### PR DESCRIPTION
**Pull request by leschbenedikt**
Resolves #157

### CODE REVIEW

File: android/app/src/main/kotlin/io/vikunja/flutteringvikunja/MainActivity.kt [hunk 1]
```diff
@@ -1,54 +1,100 @@
...
         val action: String? = intent.action
         val type: String? = intent.type
-        val channel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
 
-        if ("ACTION_INSERT" == action && type != null && "ADD_NEW_TASK" == type) {
-            if (isNewIntent) channel.invokeMethod("open_add_task", "")
-            launchMethod = "open_add_task";
+        when (action) {
+            Intent.ACTION_INSERT -> {
+                if ("ADD_NEW_TASK" == type) {
```
Comment (kolaente) [inline android/app/src/main/kotlin/io/vikunja/flutteringvikunja/MainActivity.kt]: Maybe worth adding a const for these types?

File: lib/presentation/pages/home_page.dart [hunk 2]
```diff
@@ -88,6 +99,91 @@ class HomePageState extends ConsumerState<HomePage> {
     return widgets[pos];
   }
 
+  void scheduleIntent() async {
+    try {
+      String? argument = await platform.invokeMethod<String>("isQuickTile", "");
+
+      print("Method $argument");
```
Comment (kolaente) [inline lib/presentation/pages/home_page.dart]: shouldn't this use proper logging?

**Review by kolaente — APPROVED** [review]
Thanks

**Comment by kolaente** [comment]
I noticed that when sharing multiple lines of text, only the first line would be shown in the add dialogue but all lines will be added as the task title. I assume that's a different problem, will open an issue.

EDIT: https://github.com/go-vikunja/app/issues/178
